resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: ghcr.io/berquerant/daemonjob/manager
  newTag: 0.0.1-alpha.4
configMapGenerator:
- literals:
  - BROADCAST_IMAGE_REPOSITORY=ghcr.io/berquerant/daemonjob/broadcast
  - BROADCAST_IMAGE_TAG=0.0.1-alpha.4
  - BROADCAST_ROLE=daemonjob-broadcast-role
  name: controller-manager
  options:
    disableNameSuffixHash: true
