name: Cluster Setup
description: Set up cluster
runs:
  using: "composite"
  steps:
    - name: Setup env
      uses: ./.github/actions/setup-env
    - name: Init
      run: make init
    - name: Setup go
      uses: ./.github/actions/setup-go
    - name: Create cluster
      run: make create-cluster
