apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: daemonjob
    app.kubernetes.io/managed-by: kustomize
  name: broadcast-role
rules:
- apiGroups:
  - daemonjob.berquerant.github.io
  resources:
  - daemonjobs
  - daemoncronjobs
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
