apiVersion: v2
name: daemonjob
description: Provides Job CRDs for managing cluster-wide node-local workloads
type: application
version: "0.0.1-alpha.14"
appVersion: "0.0.1-alpha.14"
kubeVersion: ">= 1.35.0-0"
keywords:
  - jobs
  - cronjobs
home: https://github.com/berquerant/daemonjob
maintainers:
  - name: berquerant
