apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "daemonjob.fullname" . }}-daemoncronjob-editor-role
  labels:
  {{- include "daemonjob.labels" . | nindent 4 }}
rules:
- apiGroups:
  - daemonjob.berquerant.github.io
  resources:
  - daemoncronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - daemonjob.berquerant.github.io
  resources:
  - daemoncronjobs/status
  verbs:
  - get
