name: Buildx Setup
description: Set up docker buildx
runs:
  using: "composite"
  steps:
    - name: Set up docker buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      with:
        buildkitd-config-inline: |
          [registry."docker.io"]
            mirrors = ["mirror.gcr.io"]
