name: Release

permissions: {}

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  KUBECONFIG: "${{ github.workspace }}/tmp/.kubeconfig"

jobs:
  init:
    outputs:
      prerelease: ${{ steps.check.outputs.prerelease }}
      version: ${{ steps.version.outputs.version }}
    timeout-minutes: 30
    permissions:
      contents: read
    name: InitRelease
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Init
        uses: ./.github/actions/setup-init
      - name: Set version
        id: version
        run: |
          echo "version=$(./hack/version.sh)" >> $GITHUB_OUTPUT
      - name: Check prerelease
        id: check
        run: |
          if echo "$ref" | grep -q -E '^v[0-9]+\.[0-9]+\.[0-9]+$' ; then
            echo "latest=true" >> "$GITHUB_OUTPUT"
            echo "prerelease=false" >> "$GITHUB_OUTPUT"
          else
            echo "latest=false" >> "$GITHUB_OUTPUT"
            echo "prerelease=true" >> "$GITHUB_OUTPUT"
          fi
        env:
          ref: ${{ github.ref_name }}

  publish:
    needs:
      - init
    timeout-minutes: 30
    permissions:
      packages: write # for ghcr
      contents: read
      id-token: write # needed for signing the images with GitHub OIDC Token
    name: Publish
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Init
        uses: ./.github/actions/setup-init
      - name: Setup go
        uses: ./.github/actions/setup-go
        with:
          cache: false
      - name: Login to ghcr
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup buildx
        uses: ./.github/actions/setup-buildx
      - name: Install Cosign
        uses: sigstore/cosign-installer@ba7bc0a3fef59531c69a25acd34668d6d3fe6f22 # v4.1.0
      - name: Build and push
        uses: ./.github/actions/build-and-push
        with:
          version: ${{ needs.init.outputs.version }}
          arch: ${{ matrix.arch }}

  merge-images:
    needs:
      - init
      - publish
    permissions:
      contents: read
      packages: write # for ghcr
      id-token: write # needed for signing the images with GitHub OIDC Token
    timeout-minutes: 30
    name: Merge images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name:
          - manager
          - broadcast
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Init
        uses: ./.github/actions/setup-init
      - name: Login to ghcr
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup buildx
        uses: ./.github/actions/setup-buildx
      - name: Install Cosign
        uses: sigstore/cosign-installer@ba7bc0a3fef59531c69a25acd34668d6d3fe6f22 # v4.1.0
      - name: Create manifest
        env:
          tag: "${{ needs.init.outputs.version }}"
        run: |
          image_name="${{ env.IMAGE_REGISTRY }}/${{ matrix.name }}"
          image="${image_name}:${tag}"
          docker buildx imagetools create -t "$image" "${image}-arm64" "${image}-amd64"
          get_digest() {
            docker buildx imagetools inspect "$image" --format='{{json .Manifest.Digest}}' | tr -d '"'
          }
          digest="$(get_digest)"
          cosign sign --yes "${image_name}:${digest}"

  test-installer:
    needs:
      - merge-images
    timeout-minutes: 30
    permissions:
      contents: read
    name: Test Installer before Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart:
          - ""
          - ./charts/daemonjob
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Test installer
        uses: ./.github/actions/test-installer
        with:
          build-images: false
          cache-go: false
          chart: ${{ matrix.chart }}

  release:
    needs:
      - init
      - merge-images
      - test-installer
    timeout-minutes: 30
    permissions:
      packages: write # for ghcr
      contents: write # for github release
    name: Release
    runs-on: ubuntu-latest
    env:
      PACKAGE: tmp/package
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true
      - name: Init
        uses: ./.github/actions/setup-init
      - name: Package the chart
        id: package-chart
        run: |
          ./hack/tool.sh helm package --destination "$PACKAGE" "./charts/daemonjob"
          echo "package_file=${PACKAGE}/daemonjob-${{ needs.init.outputs.version }}.tgz" >> $GITHUB_OUTPUT
      - name: Login to ghcr
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push chart
        env:
          package_file: ${{ steps.package-chart.outputs.package_file }}
          remote: oci://ghcr.io/berquerant/daemonjob/charts/daemonjob
        run: ./hack/tool.sh helm push "$package_file" "$remote"
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: Create release
        run: |
          extra_args=""
          if [ "$prerelease" = "true" ] ; then
            extra_args="${extra_args} --prerelease"
          fi
          gh release create "$ref" --verify-tag --generate-notes $extra_args "$package_file" "$manifest_file"
        env:
          GH_TOKEN: ${{ github.token }}
          ref: ${{ github.ref_name }}
          prerelease: ${{ needs.init.outputs.prerelease }}
          package_file: ${{ steps.package-chart.outputs.package_file }}
          manifest_file: manifests/install.yaml
