name: Installer Tests

permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  KUBECONFIG: "${{ github.workspace }}/tmp/.kubeconfig"

jobs:
  test-installer:
    timeout-minutes: 30
    permissions:
      contents: read
    name: Test Installer
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart:
          - ""
          - charts/daemonjob
    steps:
      - name: Clone the code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Test installer
        uses: ./.github/actions/test-installer
        with:
          build-images: true
          load-images: true
          docker-cache-dir: ${{ env.DOCKER_CACHE_DIR }}
          chart: ${{ matrix.chart }}
