name: Tests

permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  KUBECONFIG: "${{ github.workspace }}/tmp/.kubeconfig"

jobs:
  test:
    timeout-minutes: 30
    permissions:
      contents: read
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Init
        uses: ./.github/actions/setup-init
      - name: Setup go
        uses: ./.github/actions/setup-go
      - name: Running Tests
        run: make test

  govulncheck:
    timeout-minutes: 5
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: berquerant/govulncheck-action@7c7f559180aca72a1badcead05a3d5d81fc95c30 # v1.0.3
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
