name: E2E Tests

permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  KUBECONFIG: "${{ github.workspace }}/tmp/.kubeconfig"

jobs:
  test-e2e:
    timeout-minutes: 30
    permissions:
      contents: read
    name: E2E Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Init
        uses: ./.github/actions/setup-init
      - name: Cache docker local
        id: cache-docker-local
        uses: ./.github/actions/cache-docker-local
        with:
          path: ${{ env.DOCKER_CACHE_DIR }}
      - name: Setup buildx
        uses: ./.github/actions/setup-buildx
      - name: Setup go
        uses: ./.github/actions/setup-go
      - name: Running Test e2e
        run: make test-e2e
